name: Terraform Plan & Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      TF_LOG: INFO
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: terraform fmt -check -recursive -no-color

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_VAR_datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
          TF_VAR_datadog_app_key: ${{ secrets.DATADOG_APP_KEY }}
          TF_VAR_datadog_site: "https://api.datadoghq.com"

      # Optional: apply only if plan succeeds (uncomment if ready to apply automatically)
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   env:
      #     TF_VAR_datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
      #     TF_VAR_datadog_app_key: ${{ secrets.DATADOG_APP_KEY }}
      #     TF_VAR_datadog_site: "https://api.datadoghq.com"
