name: Terraform Plan & Apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Import existing monitors
        run: |
          terraform import datadog_monitor.cpu_high 174027331 || echo "Already imported: cpu_high"
          terraform import datadog_monitor.eth39_inbound_high_capacity 174027330 || echo "Already imported: eth39_inbound_high_capacity"

      - name: Terraform Plan
        run: terraform plan

      # Uncomment this block if you're ready to apply automatically
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main'
      #   run: terraform apply -auto-approve
